user_dir: ./user
labs:
  - multiplication_lab
experiments:
  - optimize_multiplication

log_level: INFO

# EOS orchestrator's internal web API server configuration
web_api:
  host: localhost
  port: 8070

# EOS database (MongoDB) configuration
db:
  host: localhost
  port: 27017
  username: ""
  password: ""

# EOS file database (MinIO) configuration
file_db:
  host: localhost
  port: 9004
  username: ""
  password: ""
