user_dir: ./user
labs:
  - multiplication_lab
experiments:
  - optimize_multiplication

log_level: INFO

scheduler:
  type: greedy

orchestrator_hz:
  min: 0.5 # The minimum processing rate of the orchestrator.
  max: 10  # The maximum processing rate of the orchestrator.
