name: Documentation building and deployment

on:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: pdm-project/setup-pdm@v4
        name: Set up PDM
        with:
          python-version: "3.10"
          allow-python-prereleases: false
          cache: true
          cache-dependency-path: |
            ./pdm.lock

      - name: Install dependencies
        run: pdm install --group docs --no-default

      - name: Build docs
        run: pdm run docs-build-gh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build
